export const CREATE_JOB = 'CREATE_JOB';
export const UPDATE_JOB = 'UPDATE_JOB';
export const REMOVE_JOB = 'REMOVE_JOB';

export const CREATE_SHOP_DRAWING = 'CREATE_SHOP_DRAWING';
export const UPDATE_SHOP_DRAWING = 'UPDATE_SHOP_DRAWING';
export const REMOVE_SHOP_DRAWING = 'REMOVE_SHOP_DRAWING';

export const CREATE_PHASE = 'CREATE_PHASE';
export const UPDATE_PHASE = 'UPDATE_PHASE';
export const REMOVE_PHASE = 'REMOVE_PHASE';

export const REQ_REQUISITION = 'REQ_REQUISITION';
export const REQ_REQUISITION_SUCCESS = 'REQ_REQUISITION_SUCCESS';
export const REQ_REQUISITION_ERROR = 'REQ_REQUISITION_ERROR';
export const CREATE_REQUISITION = 'CREATE_REQUISITION';
export const UPDATE_REQUISITION = 'UPDATE_REQUISITION';
export const REMOVE_REQUISITION = 'REMOVE_REQUISITION';
export const SELECT_REQUISITION = 'SELECT_REQUISITION';

export const CREATE_MANY_REQUISITION_LINE_ITEM =
  'CREATE_MANY_REQUISITION_LINE_ITEM';
export const CREATE_REQUISITION_LINE_ITEM = 'CREATE_REQUISITION_LINE_ITEM';
export const UPDATE_REQUISITION_LINE_ITEM = 'UPDATE_REQUISITION_LINE_ITEM';
export const REMOVE_REQUISITION_LINE_ITEM = 'REMOVE_REQUISITION_LINE_ITEM';

export const CREATE_VENDOR = 'CREATE_VENDOR';
export const UPDATE_VENDOR = 'UPDATE_VENDOR';
export const REMOVE_VENDOR = 'REMOVE_VENDOR';

export const CREATE_ITEM_TYPE = 'CREATE_ITEM_TYPE';
export const UPDATE_ITEM_TYPE = 'UPDATE_ITEM_TYPE';
export const REMOVE_ITEM_TYPE = 'REMOVE_ITEM_TYPE';

export const CREATE_INVENTORY_ITEM = 'CREATE_INVENTORY_ITEM';
export const UPDATE_INVENTORY_ITEM = 'UPDATE_INVENTORY_ITEM';
export const REMOVE_INVENTORY_ITEM = 'REMOVE_INVENTORY_ITEM';

export const AUTOCOMPLETE_FETCH_INIT = 'AUTOCOMPLETE_FETCH_INIT';
export const AUTOCOMPLETE_FETCH_ERROR = 'AUTOCOMPLETE_FETCH_ERROR';
export const AUTOCOMPLETE_FETCH_SUCCESS = 'AUTOCOMPLETE_FETCH_SUCCESS';

export const SAVE_QUERY = 'SAVE_QUERY';
